name: Automatic testing with Jest

on: [pull_request, workflow_dispatch]

jobs:
  run-jest-tests:
    name: Jest tests    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@4.2.0
        with:
          node-version: 20

      - name: Install all dependencies
        run: npm install

      - name: Run Jest tests
        run: npm run test
